name: model-training-evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train and Evaluate model'
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.DATA_REPO_SECRET }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from Google Drive and reproduce pipeline
          dvc pull
          dvc repro

          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff main --show-md >> report.md

          # Publish confusion matrix diff
          echo -e "## Plots\n### ROC Curve" >> report.md
          cml-publish ./results/roc_curve.png --md >> report.md
          echo -e "\n### Precision and Recall Curve" >> report.md
          cml-publish ./results/precision_recall_curve.png --md >> report.md
          cml-send-comment report.md
